### PR TITLE
Feature/olp 50 line point removal is broken in some circumstances other

### PR DESCRIPTION
**Pull request by TheNewCivilian**
Many smaller fixxes, that improve the user experience significantly

### CODE REVIEW

**Review by zandemax — CHANGES_REQUESTED** [review]
Unfortunately the z-Indices problem is not completely fixed yet, otherwise this looks good!
See comment in linear: https://linear.app/xatellite/issue/OLP-50#comment-a0189c05

**Comment by TheNewCivilian** [comment]
Oh this did not include any work related to the z-index bug.. that should be a separate issue https://linear.app/xatellite/issue/OLP-55/fix-z-indexes-on-map

**Comment by zandemax** [comment]
Huh you are right, i just noticed while testing that the z-index problem improved significantly, thought that was in this PR :D

**Review by zandemax — APPROVED** [review]

**Comment by zandemax** [comment]
Then this is ready to merge :)

**Pull request merged**
